# Purpose run "autopkg" to update a Munki repository
version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.0"

    steps:
      - checkout
      - run:
          name: fetch_autopkg
          command: |
            curl -L https://github.com/autopkg/autopkg/releases/download/v1.0.4/autopkg-1.0.4.pkg > ./autopkg-1.0.4.pkg
      - run:
          name: install_autopkg
          command: sudo installer -pkg ./autopkg-1.0.4.pkg -target /
      - run:
          name: run_autopkg_fetch_repos
          command: /usr/local/bin/autopkg repo-add https://github.com/autopkg/recipes.git
      - run:
          name: run_autopkg_list_repos
          command: /usr/local/bin/autopkg list-recipes

workflows:
  version: 2
  build-test-run:
    jobs:
      - build-and-test
