version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.0"

    steps:
      - checkout
      - run:
          name: fetch_autopkg
          command: |
            curl https://github.com/autopkg/autopkg/releases/download/v1.0.4/autopkg-1.0.4.pkg > ./autopkg-1.0.4.pkg
      - run:
          name: extract_autopkg
          command: pkgutil --expand ./autopkg-1.0.4.pkg ./autopkg
      - run:
          name: run_autopkg_update_munki
          command: echo "Hello World"

workflows:
  version: 2
  build-test-run:
    jobs:
      - build-and-test
