version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.0"

    steps:
      - checkout
      - run:
          name: Fetch CocoaPods Specs
          command: |
            curl https://github.com/autopkg/autopkg/releases/download/v1.0.4/autopkg-1.0.4.pkg > ./autopkg-1.0.4.pkg
      # | bash -s cf
      - run:
          name: extract_autopkg
          command: pkgutil –expand ./autopkg-1.0.4.pkg ./autopkg

workflows:
  version: 2
  build-test-lint:
    jobs:
      - build-and-test
      