# Purpose run "autopkg" to update a Munki repository
version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.0"

    steps:
      - checkout
      - run:
          name: fetch_munki
          command: |
            curl -L https://munkibuilds.org/munkitools3-latest.pkg > munkitools3-latest.pkg > ./munkitools3-latest.pkg
      - run:
          name: install_munki
          command: sudo installer -pkg ./munkitools3-latest.pkg -target /
      - run:
          name: Setup Environment Variables
          command: |
            echo 'export MUNKI_REPO="file:///tmp/munki"' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: create_repo
          command: mkdir /tmp/munki
      - run:
          name: configure_munki
          command: sudo /usr/bin/defaults write /Library/Preferences/ManagedInstalls SoftwareRepoURL 'file:///tmp/munki'
      - run:
          name: fetch_autopkg
          command: |
            curl -L https://github.com/autopkg/autopkg/releases/download/v1.0.4/autopkg-1.0.4.pkg > ./autopkg-1.0.4.pkg
      - run:
          name: install_autopkg
          command: sudo installer -pkg ./autopkg-1.0.4.pkg -target /
      - run:
          name: run_autopkg_fetch_repos
          command: /usr/local/bin/autopkg repo-add https://github.com/autopkg/recipes.git
      - run:
          name: run_autopkg_list_repos
          command: /usr/local/bin/autopkg list-recipes
      - run:
          name: run_autopkg_run_recipies
          command: /usr/local/bin/autopkg run Firefox.munki
          environment:
            MUNKI_REPO: "file:///tmp/munki"

workflows:
  version: 2
  build-test-run:
    jobs:
      - build-and-test

# munkiimport --configure --repo_url=/Users/gyoung/src/macos/repo
# Repo URL (example: afp://munki.example.com/repo): file:////Users/gyoung/src/macos/repo
# pkginfo extension (Example: .plist):
# pkginfo editor (examples: /usr/bin/vi or TextMate.app; leave empty to not open an editor after import):
# Default catalog to use (example: testing):
# Repo access plugin (defaults to FileRepo):
